ARG buildno
#ARG gitcommithash

FROM node:latest

RUN echo "Build number: $buildno"
#RUN echo "Based on commit: $gitcommithash"

WORKDIR /usr/src/prisma

COPY package.json ./
COPY tsconfig.json ./
COPY graphqlgen.yml ./
COPY .env* ./

RUN npm install
RUN npm audit fix

ENV PRISMA_MANAGEMENT_API_SECRET="my-secret"

EXPOSE 4000